export const NOTES_LIST_REQUEST = 'NOTES_LIST_REQUEST';
export const NOTES_LIST_SUCCESS = 'NOTES_LIST_SUCCESS';
export const NOTES_LIST_FAIL = 'NOTES_LIST_FAIL';

export const NOTES_DETAIL_REQUEST = 'NOTES_DETAIL_REQUEST';
export const NOTES_DETAIL_SUCCESS = 'NOTES_DETAIL_SUCCESS';
export const NOTES_DETAIL_FAIL = 'NOTES_DETAIL_FAIL';

export const NOTES_UPDATE_INPUTBOX = 'NOTES_UPDATE_INPUTBOX';
export const NOTES_UPDATE_FILENAME = 'NOTES_UPDATE_FILENAME';
export const NOTES_UPDATE_FAVOURITE = 'NOTES_UPDATE_FAVOURITE';

export const NOTES_UPDATE_REQUEST = 'NOTES_UPDATE_REQUEST';
export const NOTES_UPDATE_SUCCESS = 'NOTES_UPDATE_SUCCESS';
export const NOTES_UPDATE_FAIL = 'NOTES_UPDATE_FAIL';

export const NOTES_CREATE_REQUEST = 'NOTES_CREATE_REQUEST';
export const NOTES_CREATE_SUCCESS = 'NOTES_CREATE_SUCCESS';
export const NOTES_CREATE_FAIL = 'NOTES_CREATE_FAIL';