# Generated by Django 3.2.9 on 2021-12-05 15:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('favourite', models.BooleanField(default=False)),
                ('global_file', models.BooleanField(default=False)),
                ('content', models.TextField(default=' ')),
                ('style_screen_backgroundColor', models.CharField(default='#ffc7c7', max_length=8)),
                ('style_screen_paddingTop', models.CharField(default='20px', max_length=8)),
                ('style_box_backgroundColor', models.CharField(default='#80ffd4', max_length=8)),
                ('style_box_maxWidth', models.CharField(default='100px', max_length=8)),
                ('style_box_padding', models.CharField(default='10px', max_length=8)),
                ('style_box_borderWidth', models.CharField(default='5px', max_length=8)),
                ('style_box_borderColor', models.CharField(default='#008066', max_length=8)),
                ('style_box_borderTopLeftRadius', models.CharField(default='20px', max_length=8)),
                ('style_box_borderTopRightRadius', models.CharField(default='20px', max_length=8)),
                ('style_box_borderBottomLeftRadius', models.CharField(default='20px', max_length=8)),
                ('style_box_borderBottomRightRadius', models.CharField(default='20px', max_length=8)),
                ('style_line_backgroundColor', models.CharField(default='#80ffd4', max_length=8)),
                ('style_line_width', models.CharField(default='10px', max_length=8)),
                ('style_text_color', models.CharField(default='#121212', max_length=8)),
                ('style_text_fontSize', models.CharField(default='15px', max_length=8)),
                ('style_text_fontWeight', models.CharField(default='2px', max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='shared_with',
            field=models.ManyToManyField(blank=True, to='base.Notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
